---
title: "Results of the analysis of AIS data 2015-2019"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 3
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
library(leaflet)
library(sf)
library(ggplot2)
library(dplyr)
library(raster)

wgs = "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"

ref_gsa = paste0("GSA", c(12:16, 18:27))
#Land ####
land = read_sf("maps/land/ne_10m_admin_0_countries.shp")
st_crs(land) = wgs
#GSA ####
ref_gsa = paste0("GSA", c(12:16, 18:27))
gsa = read_sf("maps/gsas/gsas.shp")
gsa = gsa[which(gsa$SECT_COD %in% ref_gsa),]
st_crs(gsa) = wgs
sicily = c("GSA12", "GSA13", "GSA15", "GSA16")
ionian = c("GSA18", "GSA19", "GSA20", "GSA21")
aegean = c("GSA22", "GSA23")
levantine = c("GSA24", "GSA25")
gsa_sicily = gsa %>% filter(SECT_COD %in% sicily)
sicily_centers = st_centroid(gsa_sicily)
gsa_ionian = gsa %>% filter(SECT_COD %in% ionian)
ionian_centers = st_centroid(gsa_ionian)
gsa_aegean = gsa %>% filter(SECT_COD %in% aegean)
aegean_centers = st_centroid(gsa_aegean)
gsa_levantine = gsa %>% filter(SECT_COD %in% levantine)
levantine_centers = st_centroid(gsa_levantine, )
```

## Assessment at GSAs levels {.tabset}

### Strait of Sicily (GSA12, GSA13, GSA15, GSA16)
```{r echo=FALSE}
leaflet(gsa_sicily) %>%
  setView(lng = sicily_centers$geometry[[1]][1], lat = sicily_centers$geometry[[1]][2], zoom = 6) %>%
  addTiles(group = "base") %>%
  addPolygons(color = "#444444", 
              weight = 1, 
              smoothFactor = 0.5,
              opacity = 1.0, group = "GSAs") %>%
  addLabelOnlyMarkers(data = sicily_centers, label = ~SECT_COD,
                      labelOptions = labelOptions(noHide = TRUE, direction = 'top', textOnly = TRUE), 
                      group = "GSAs") %>%
  addLayersControl(baseGroups = c("base"),
                   overlayGroups = c("GSAs"),
                   options = layersControlOptions(collapsed = FALSE)) 
```
### Ionian Sea (GSA18, GSA19, GSA20, GSA21)
```{r echo=FALSE}
leaflet(gsa_ionian) %>%
  setView(lng = ionian_centers$geometry[[1]][1], lat = ionian_centers$geometry[[1]][2], zoom = 6) %>%
  addTiles(group = "base") %>%
  addPolygons(color = "#444444", 
              weight = 1, 
              smoothFactor = 0.5,
              opacity = 1.0, group = "GSAs")  %>%
  addLabelOnlyMarkers(data = ionian_centers, label = ~SECT_COD,
                      labelOptions = labelOptions(noHide = TRUE, direction = 'top', textOnly = TRUE), 
                      group = "GSAs") %>%
  addLayersControl(baseGroups = c("base"),
                   overlayGroups = c("GSAs"),
                   options = layersControlOptions(collapsed = FALSE)) 
```
### Aegean Sea (GSA22, GSA23)
```{r echo=FALSE}
leaflet(gsa_aegean) %>%
  setView(lng = aegean_centers$geometry[[1]][1], lat = aegean_centers$geometry[[1]][2], zoom = 6) %>%
  addTiles(group = "base") %>%
  addPolygons(color = "#444444", 
              weight = 1, 
              smoothFactor = 0.5,
              opacity = 1.0, group = "GSAs")  %>%
  addLabelOnlyMarkers(data = aegean_centers, label = ~SECT_COD,
                      labelOptions = labelOptions(noHide = TRUE, direction = 'top', textOnly = TRUE), 
                      group = "GSAs") %>%
  addLayersControl(baseGroups = c("base"),
                   overlayGroups = c("GSAs"),
                   options = layersControlOptions(collapsed = FALSE)) 
```
### Northern Levantine Sea (GSA24, GSA25)
```{r echo=FALSE}
leaflet(gsa_levantine) %>%
  setView(lng = levantine_centers$geometry[[1]][1], lat = levantine_centers$geometry[[1]][2], zoom = 6) %>%
  addTiles(group = "base") %>%
  addPolygons(color = "#444444", 
              weight = 1, 
              smoothFactor = 0.5,
              opacity = 1.0, group = "GSAs") %>%
  addLabelOnlyMarkers(data = levantine_centers, label = ~SECT_COD,
                      labelOptions = labelOptions(noHide = TRUE, direction = 'top', textOnly = TRUE), 
                      group = "GSAs") %>%
  addLayersControl(baseGroups = c("base"),
                   overlayGroups = c("GSAs"),
                   options = layersControlOptions(collapsed = FALSE)) 
```